client:
  address: https://localhost:9443/codenotfound/ws/ticketagent
  trust-store: classpath:jks/client-truststore.jks
  trust-store-password: client-truststore-p455w0rd

server:
  port: 9443
  ssl:
    key-store: classpath:jks/server-keystore.jks
    key-store-password: server-keystore-p455w0rd
    key-alias: server-keypair
    key-password: server-key-p455w0rd

cxf:
  path: /codenotfound/ws
