client:
  ticketagent:
    address: http://localhost:9090/codenotfound/ws/ticketagent
    keystore-alias: client-keypair

server:
  port: 9090
  ticketagent:
    keystore-alias: server-keypair

cxf:
  path: /codenotfound/ws
