client:
  ticketagent:
    address: http://localhost:9090/codenotfound/ws/ticketagent
    user-name: codenotfound
    password: p455w0rd

security:
  user:
    name: codenotfound
    password: p455w0rd

server:
  port: 9090

cxf:
  path: /codenotfound/ws
